apiVersion: v1
kind: Service
metadata:
  name: it-tools
  namespace: homelab
  labels:
    app: it-tools
spec:
  type: NodePort
  selector:
    app: it-tools
  ports:
    - name: http
      port: 80        # cluster içi port
      targetPort: 80  # pod’daki port
      nodePort: 30005 # dışarıdan bu port ile erişim
