apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitea
  namespace: homelab
  labels:
    app: gitea
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitea
  template:
    metadata:
      labels:
        app: gitea
    spec:
      containers:
      - name: gitea
        image: gitea/gitea:1.22.4
        ports:
          - containerPort: 3000   # HTTP
          - containerPort: 22     # SSH
        env:
          - name: USER_UID
            value: "1000"
          - name: USER_GID
            value: "1000"
          - name: GITEA__security__INSTALL_LOCK
            value: "true"
          - name: GITEA__database__DB_TYPE
            value: "sqlite3"
        volumeMounts:
          - name: data
            mountPath: /data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: gitea-pvc
