apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud
  namespace: homelab
  labels:
    app: nextcloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextcloud
  template:
    metadata:
      labels:
        app: nextcloud
    spec:
      containers:
      - name: nextcloud
        image: nextcloud:25-apache
        ports:
          - containerPort: 80
        volumeMounts:
          - name: data
            mountPath: /var/www/html/data
          - name: config
            mountPath: /var/www/html/config
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: nextcloud-data-pvc
        - name: config
          persistentVolumeClaim:
            claimName: nextcloud-config-pvc
