apiVersion: apps/v1
kind: Deployment
metadata:
  name: home-assistant
  namespace: homelab
  labels:
    app: home-assistant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: home-assistant
  template:
    metadata:
      labels:
        app: home-assistant
    spec:
      containers:
      - name: home-assistant
        image: homeassistant/home-assistant:stable
        ports:
          - containerPort: 8123
        volumeMounts:
          - name: config
            mountPath: /config
          - name: media
            mountPath: /media
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: home-assistant-config-pvc
        - name: media
          persistentVolumeClaim:
            claimName: home-assistant-media-pvc
