apiVersion: v1
kind: Service
metadata:
  name: home-assistant
  namespace: homelab
  labels:
    app: home-assistant
spec:
  type: NodePort
  selector:
    app: home-assistant
  ports:
    - name: ui
      port: 8123
      targetPort: 8123
      nodePort: 30004
