apiVersion: v1
kind: Service
metadata:
  name: uptimekuma
  namespace: homelab
  labels:
    app: uptimekuma
spec:
  type: NodePort
  selector:
    app: uptimekuma
  ports:
    - name: http
      port: 3001
      targetPort: 3001
      nodePort: 30006
