services:
  gitea:
    image: gitea/gitea:1.22.4
    container_name: gitea
    env_file:
      - .env
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=sqlite3
      - GITEA__security__INSTALL_LOCK=true
      - GITEA__server__ROOT_URL=http://localhost:${GITEA_HTTP_PORT}
      - GITEA__security__INTERNAL_TOKEN=change_me
      - GITEA_ADMIN_USER=${GITEA_ADMIN_USER}
      - GITEA_ADMIN_PASSWORD=${GITEA_ADMIN_PASS}
    volumes:
      - ${GITEA_DATA}:/data
    ports:
      - "${GITEA_HTTP_PORT}:3000"
      - "${GITEA_SSH_PORT}:22"
    restart: unless-stopped